// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package awsservices.actions;

import java.util.LinkedList;
import java.util.List;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import awsservices.impl.AWSClients;
import awsservices.impl.AWSHelper;
import awsservices.impl.S3Helper;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.ListObjectsRequest;
import software.amazon.awssdk.services.s3.model.ListObjectsResponse;

public class S3_ListObjects extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __credentials;
	private awsservices.proxies.Credentials credentials;
	private java.lang.String bucket;
	private java.lang.String prefix;

	public S3_ListObjects(IContext context, IMendixObject credentials, java.lang.String bucket, java.lang.String prefix)
	{
		super(context);
		this.__credentials = credentials;
		this.bucket = bucket;
		this.prefix = prefix;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.credentials = __credentials == null ? null : awsservices.proxies.Credentials.initialize(getContext(), __credentials);

		// BEGIN USER CODE
		S3Client client = AWSClients.getS3Client(getContext(), credentials);
		ListObjectsRequest req = 
				ListObjectsRequest.builder().bucket(bucket).prefix(prefix).build();

		List<IMendixObject> result = new LinkedList<>();
		ListObjectsResponse res = client.listObjects(req);
		for (software.amazon.awssdk.services.s3.model.S3Object obj : res.contents()) {
			result.add(S3Helper.getMxS3Object(
					getContext(), obj, bucket).getMendixObject());
		}
		if (res.isTruncated()) {
			AWSHelper.LOGGER.error("List has been truncated!");
		}
		
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "S3_ListObjects";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
