// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package awsservices.actions;

import java.util.Collections;
import java.util.stream.Collectors;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import awsservices.impl.AWSClients;
import awsservices.proxies.Topic;
import software.amazon.awssdk.arns.Arn;
import software.amazon.awssdk.services.sns.SnsClient;
import software.amazon.awssdk.services.sns.model.ListTopicsResponse;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class SNS_ListTopics extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __credentials;
	private awsservices.proxies.Credentials credentials;

	public SNS_ListTopics(IContext context, IMendixObject credentials)
	{
		super(context);
		this.__credentials = credentials;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.credentials = __credentials == null ? null : awsservices.proxies.Credentials.initialize(getContext(), __credentials);

		// BEGIN USER CODE
		final SnsClient client = AWSClients.getSnsClient(getContext(), credentials);

		final ListTopicsResponse response = client.listTopics();

		return !response.hasTopics() ? Collections.emptyList() :
			response.topics().stream().map(x -> {
				final Arn arn = Arn.fromString(x.topicArn());
				final Topic topic = new Topic(getContext());
				topic.setArn(x.topicArn());
				topic.setName(arn.resourceAsString());
				return topic.getMendixObject();
			}).collect(Collectors.toList());
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SNS_ListTopics";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
