// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package awsservices.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import awsservices.impl.AWSClients;
import software.amazon.awssdk.services.sqs.SqsClient;
import software.amazon.awssdk.services.sqs.model.DeleteMessageRequest;

public class SQS_DeleteMessage extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __credentials;
	private awsservices.proxies.Credentials credentials;
	private java.lang.String queueUrl;
	private java.lang.String receiptHandle;

	public SQS_DeleteMessage(IContext context, IMendixObject credentials, java.lang.String queueUrl, java.lang.String receiptHandle)
	{
		super(context);
		this.__credentials = credentials;
		this.queueUrl = queueUrl;
		this.receiptHandle = receiptHandle;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.credentials = __credentials == null ? null : awsservices.proxies.Credentials.initialize(getContext(), __credentials);

		// BEGIN USER CODE
		SqsClient sqs = AWSClients.getSqsClient(getContext(), credentials);
		
		DeleteMessageRequest dmr = DeleteMessageRequest.builder()
				.queueUrl(queueUrl)
				.receiptHandle(receiptHandle)
				.build();
		sqs.deleteMessage(dmr);
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "SQS_DeleteMessage";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
